version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: criptogt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb/schema.sql:/docker-entrypoint-initdb.d/schema.sql # Caminho corrigido
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d criptogt"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: senha
      DB_NAME: criptogt
      DB_PORT: 5432
      JWT_SECRET: criptogtsecret
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: